# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: AWS CLI
    init: |
      (
      cd /home/gitpod
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      )
vscode:
  extensions:
    - hashicorp.terraform
    - dbaeumer.vscode-eslint@2.4.0
    - DavidAnson.vscode-markdownlint@0.49.0
    - esbenp.prettier-vscode
    - mcright.auto-save
