# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: AWS CLI
    init: echo 'AWS CLI' # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
    command: >
      cd ~ ;
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" ;
      unzip awscliv2.zip ;
      sudo ./aws/install


