# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: AWS CLI
    command: |
      (
      cd /home/gitpod
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      )
       
  - name: Terraform
    command: |
      (
      wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
      echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
      sudo apt update && sudo apt install terraform
      )      
vscode:
  extensions:
    - hashicorp.terraform
    - dbaeumer.vscode-eslint@2.4.0
    - DavidAnson.vscode-markdownlint@0.49.0
    - esbenp.prettier-vscode
    - mcright.auto-save
